package authsystem.auth;

import authsystem.model.User;

/**
 * OtpAuth class
 * -------------
 * Implements the AuthStrategy interface to provide OTP (One-Time Password) based authentication.
 *
 * Features:
 * - Compares a generated OTP with the entered OTP.
 * - Tracks failed login attempts.
 * - Locks the account after exceeding maximum allowed failed attempts.
 *
 * This demonstrates the Strategy Design Pattern, where different authentication
 * mechanisms (password, OTP, biometric, etc.) can be implemented independently.
 */
public class OtpAuth implements AuthStrategy {

    // Maximum number of failed login attempts before account is locked
    private static final int MAX_FAILED_ATTEMPTS = 3;

    // The OTP generated by the system
    private final String generatedOtp;

    // The OTP entered by the user
    private final String enteredOtp;

    /**
     * Constructor to initialize OTP values.
     *
     * @param generatedOtp The OTP generated by the system
     * @param enteredOtp   The OTP entered by the user
     */
    public OtpAuth(String generatedOtp, String enteredOtp) {
        this.generatedOtp = generatedOtp;
        this.enteredOtp = enteredOtp;
    }

    /**
     * Authenticate the user based on OTP comparison.
     *
     * @param user The user attempting to log in
     * @return true if authentication succeeds, false otherwise
     */
    @Override
    public boolean authenticate(User user) {
        // If account is already locked, deny access
        if (user.isAccountLocked()) {
            return false;
        }

        // If OTP matches, reset failed attempts and allow login
        if (generatedOtp.equals(enteredOtp)) {
            user.resetFailedAttempts();
            return true;
        }

        // If OTP does not match, increment failed attempts
        user.incrementFailedAttempts();

        // Lock account if failed attempts exceed maximum threshold
        if (user.getFailedAttempts() >= MAX_FAILED_ATTEMPTS) {
            user.lockAccount();
        }

        // Authentication failed
        return false;
    }
}